apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-reactproject
  template:
    metadata:
      labels:
        app: my-reactproject
    spec:
      containers:
      - name: my-container-lb
        image: tayefajem/seun:1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-reactproject
  labels:
    app: my-reactproject
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "4"
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "svc"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # Port to access from outside
      targetPort: 3000 # Port inside container
  selector:
    app: my-reactproject

